### PR TITLE
This fixes #25

### LINKED ISSUE #25: TypeError - no implicit conversion of true into Hash:
I get this error in rails console after below query  and UI is coming blank
<code>
Sidekiq::Monitor::Job Load (1.3ms)  SELECT  `sidekiq_jobs`.\* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`queue` = 'legacy_importer'  ORDER BY sidekiq_jobs.enqueued_at DESC LIMIT 10 OFFSET 0 Completed 500 Internal Server Error in 16ms  
TypeError - no implicit conversion of true into Hash:
</code>
My worker has this code at the end 

{
        message: "#{users.count} users processed"
}

Output of Sidekiq::Monitor::Job.all in rails console 

  "Sidekiq::Monitor::Job.all
  Sidekiq::Monitor::Job Load (0.4ms)  SELECT `sidekiq_jobs`.\* FROM `sidekiq_jobs`

Sidekiq::Monitor::Job id: 3, jid: "f8f21eba5547390451721801", queue: "legacy_importer", class_name: "LegacyUserWorker", args: [], retry: true, enqueued_at: "2014-06-17 12:33:04", started_at: "2014-06-17 12:34:38", finished_at: "2014-06-17 12:34:45", status: "complete", name: nil, result: {:message=>"526 users processed"}

### PR DESCRIPTION
**Pull request by harssh**

### CODE REVIEW

**Comment by abrambailey** [comment]
Hopefully someone hears you.

**Comment by tombenner** [comment]
Thanks for submitting this! It would unfortunately break in Rails 3 apps, though, in which the third argument of `distance_of_time_in_words` [is a boolean](https://github.com/rails/rails/blob/bd8a9701c27b4261e9d8dd84aebbde6ba784ed83/actionpack/lib/action_view/helpers/date_helper.rb#L67). If you'd like to fix this, perhaps you could open a new PR that contains something like:

``` ruby
if Rails::VERSION::MAJOR >= 4
  words = distance_of_time_in_words(from_time, to_time, include_seconds: true)
else
  words = distance_of_time_in_words(from_time, to_time, true)
end
words.gsub('less than ', '').gsub('about ', '')
```

I'd rather we didn't add this onto this PR, so that we can keep the revision history clean. If you don't have time to do this soon, I can probably do it within the next couple of days. Thanks!

**Comment by abrambailey** [comment]
Tom, please pull https://github.com/socialpandas/sidekiq_monitor/pull/28

**Comment by harssh** [comment]
@tombenner  No problem I will add that to PR

**Comment by harssh** [comment]
@tombenner  Thanx for the suggestion I have added suggested changes ...
Apprecite it :+1:

**Comment by harssh** [comment]
You can merge this PR now

**Comment by tombenner** [comment]
Thanks! #28 was cleaner (it removed the original faulty line), so I've merged that. The new release (0.1.5) contains this fix.

**Pull request closed without merging**
